apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-8nl4
  namespace: e2e-demos-ejcw-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:35deef0cd06ac9fdb75d4f1eb4babbe58f64f7db23a59e1ba3738fef1cc4244b
        name: my-java-quarkus
        resources: {}
status: {}
